import os
import streamlit as st
from langchain_groq import ChatGroq
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from langchain_community.vectorstores import FAISS

# configuration
INDEX_PATH = "rag/faiss_index" 
MODEL_NAME = "all-MiniLM-L6-v2"
GROQ_MODEL = "groq/compound-mini"
GITHUB_REPO_URL = "https://github.com/datagranate/data-portfolio" 

st.set_page_config(page_title="FCA COBS Compliance Assistant", page_icon="🏛️", layout="wide")
st.title("FCA COBS Compliance Assistant")
st.markdown("""
This app answers questions based on the **UK FCA Handbook (COBS Chapters 1-10A)**.
""")

# Secrets
api_key = st.secrets.get("GROQ_API_KEY")
if not api_key:
    st.warning("**API key missing**: Please set `GROQ_API_KEY` in Streamlit Cloud settings.")
    st.stop()
os.environ["GROQ_API_KEY"] = api_key

@st.cache_resource
def load_vector_store():
    with st.spinner("Loading compliance knowledge base..."):
        try:
            embeddings = HuggingFaceEmbeddings(model_name=MODEL_NAME)
            vector_store = FAISS.load_local(
                INDEX_PATH, 
                embeddings, 
                allow_dangerous_deserialization=True
            )
            
            # quick sanity check (silent)
            if len(vector_store.docstore._dict) == 0:
                st.error("Index is empty. Please check the data source.")
                return None
                
            return vector_store
        except Exception as e:
            st.error(f"Failed to load index: {e}")
            return None

vector_store = load_vector_store()

if vector_store is None:
    st.stop()

llm = ChatGroq(model_name=GROQ_MODEL, temperature=0)

# RAG chain
prompt = ChatPromptTemplate.from_messages([
    ("system", """You are a professional UK Financial Compliance Assistant. 
Answer the user's question using ONLY the provided context from the FCA COBS handbook (Chapters 1-10A).
    
CRITICAL INSTRUCTIONS:
1. Do NOT start your answer with phrases like "Based on the context," "Based on the provided text," or "According to the documents."
2. Start your answer **directly** with the factual information.
3. If the answer is not in the context, simply state: "I cannot find this information in the provided COBS chapters."
4. Do not hallucinate. Be precise and professional.

Context: {context}
Question: {question}

Helpful answer:"""),
    ("human", "{question}")
])

retriever = vector_store.as_retriever(search_kwargs={"k": 6})

rag_chain = (
    {"context": retriever, "question": RunnablePassthrough()}
    | prompt 
    | llm 
    | StrOutputParser()
)

# Chat UI
if "messages" not in st.session_state:
    st.session_state.messages = []

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

if prompt := st.chat_input("Ask a question about COBS (eg, 'What are the rules on inducements?'):"):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        with st.spinner("Searching FCA Handbook..."):
            try:
                # get the raw context to debug
                context_docs = retriever.invoke(prompt)
                context_text = "\n\n".join([doc.page_content for doc in context_docs])

                response = rag_chain.invoke(prompt)
                st.markdown(response)
                st.session_state.messages.append({"role": "assistant", "content": response})
            except Exception as e:
                st.error(f"An error occurred: {e}")

# Sidebar

logo_path = "images/datagranate_small_100.png"
if logo_path.exists():
    try:
        st.sidebar.logo(str(logo_path), width=100)
    except AttributeError:
        st.sidebar.image(str(logo_path), width=150)

st.sidebar.markdown("---")

# about
st.sidebar.header("About this demo")
st.sidebar.markdown("""
This application is a practical demonstration of **RAG pipeline implementation**, focusing on 
**data engineering** and **AI integration**.

**Knowledge base:**
- **Source:** UK Financial Conduct Authority (FCA) Handbook [view FCA Handbook online]("https://handbook.fca.org.uk/handbook")
- **Section:** Conduct of Business Sourcebook (COBS), Chapters 1–10A.
- **Version:** Last updated 5 August 2026.
""".format()
)

st.sidebar.markdown("---")

# disclaimer
st.sidebar.warning("""
**Disclaimer:**
This tool is for **demonstration and portfolio purposes only**. 
- It is **NOT** a legal advice tool.
- Answers are generated by an AI and may contain errors.
- Do not rely on these responses for actual financial compliance decisions.
""")

st.sidebar.markdown("---")

# portfolio
st.sidebar.success("**View the source code**")
st.sidebar.markdown(f"[Visit my data portfolio]({GITHUB_REPO_URL})")
st.sidebar.markdown("*Built with LangChain, FAISS, and Streamlit.*")

